name: remiksweb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/remiks_logo.png
    - assets/chili_shots.png
    - assets/sawsaw_suka.png
    - assets/hot_sauce.png
    - assets/ginisang_alamang.png
    - assets/chicken_pastil.png
    - assets/chili_garlic.png
    - assets/facebook.png
    - assets/background_intro_raw.webp
    - assets/remiks_vision.webp

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Black.ttf
    - family: Bitshow
      fonts:
        - asset: assets/Bitshow.ttf
    - family: Hey
      fonts:
        - asset: assets/Hey Comic.ttf
