name: remiksweb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_osm_plugin: ^1.3.6
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.1.0
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/remiks_logo.png
    - assets/chili_shots.png
    - assets/sawsaw_suka.png
    - assets/hot_sauce.png
    - assets/ginisang_alamang.png
    - assets/chicken_pastil.png
    - assets/chili_garlic.png
    - assets/facebook.png
    - assets/background_intro_raw.webp
    - assets/remiks_vision.webp
    - assets/banner.png
    - assets/remiks_about_us.webp
    - assets/fb_page.png
    - assets/effectbg.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Black.ttf
    - family: Bitshow
      fonts:
        - asset: assets/Bitshow.ttf
    - family: Hey
      fonts:
        - asset: assets/Hey Comic.ttf
    - family: Soft
      fonts:
        - asset: assets/Softizen.ttf
